# Match the database name you created
spring.datasource.url=jdbc:mysql://localhost:3306/myapp_db

# Use the specific user and password from your SQL commands
spring.datasource.username=myuser
spring.datasource.password=mypassword

# Recommended settings for your BCA project
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

gemini.api.key=AIzaSyByHcuVwFRYEnu97DZLmTJUPgL4BcM2pAs 
# spring.application.name=backend

# spring.datasource.url=jdbc:mysql://localhost:3306/script_video_db?allowPublicKeyRetrieval=true&useSSL=false
# spring.datasource.username=root
# spring.datasource.password=SAMIR
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.servlet.multipart.max-file-size=10MB
# spring.servlet.multipart.max-request-size=10MB
# server.port=8080